server:
  port: 10086
spring:
  application:
    name: halk-eureka  # 作为微服务名称注入到容器
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.114:10086/eureka
  server:
    eviction-interval-timer-in-ms: 5000  # 失效服务剔除时间间隔
    enable-self-preservation: false  # 关闭自我保护状态
