server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false  # 开发时禁用缓存，部署时打开
  rabbitmq:
    host: 192.168.25.152
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    registry-fetch-interval-seconds: 5  # 拉取服务的时间
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 租约续约时间（心跳时间）
    lease-expiration-duration-in-seconds: 15  # 租约终结持续时间（过期时间）
