server:
  port: 10010
spring:
  application:
    name: halk-zuul
zuul:
  routes:  # \u8DEF\u7531\u540D\u79F0\uFF0C\u53EF\u4EE5\u968F\u4FBF\u5199\uFF0C\u4E60\u60EF\u4E0A\u670D\u52A1\u540D
    service-provider: /user/**
      # path: /service-provider/**
      # url: http://localhost:8081
      # serviceId: service-provider
    service-consumer: /consumer/**
      # path: /service-consumer/**
      # serviceId: service-consumer
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.114:10086/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # \u8BBE\u7F6Ehystrix\u7684\u8D85\u65F6\u65F6\u95F4\u4E3A5000ms\uFF0C\u9ED8\u8BA4\u53EA\u67091\u79D2\u949F