server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10  # 拉取服务的时间
  instance:
    lease-renewal-interval-in-seconds: 5  # 心跳
    lease-expiration-duration-in-seconds: 15  # 过期时间
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa%hacker # 登录校验的密钥
    pubKeyPath: D:\\projects\\halk_study\\code\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\projects\\halk_study\\code\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
