server:
  port: 8083
spring:
  application:
    name: upload-service  # 微服务名称
  servlet:
    multipart:
      max-file-size: 5MB  # 文件大小
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  # 心跳检测
    lease-expiration-duration-in-seconds: 15  # 租期续约时间
fdfs:
  connect-timeout: 601  # 连接超时时间
  so-timeout: 1501  # 读取超时时间
  thumb-image:  # 缩略图
    width: 60
    height: 60
  tracker-list:  # tracker地址：你的虚拟机服务器地址+端口号（默认端口号22122）
    - 192.168.25.152:22122
