spring:
  datasource:
    username: root
    password: uetec123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/shexian_oa

server:
  port: 1111

mybatis:
  mapper-locations: classpath*:mapper/*.xml
